# Read pre-commit hook framework https://pre-commit.com/ for more details about the structure of config yaml file and how git pre-commit would invoke each hook.
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: check-added-large-files
      exclude: &exclude_venv .venv/.*|.git/.*
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: detect-private-key
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: *exclude_venv
-   repo: local
    hooks:
    -   id: bom-radar-scraper
        name: BOM Radar Scraper
        entry: ./bom_radar_scraper.py
        language: python
        additional_dependencies: [requests]
        stages: [pre-commit]
        always_run: true
